name: dataplus

channels:
- conda-forge
- anaconda


dependencies:
# Essential
- python==3.10.0
- pip==21.3.1
- nb_conda_kernels==2.3.1
# Data Science
- numpy==1.21.4
- scipy==1.7.2
- pandas==1.3.4
# Visualization
- matplotlib==3.5.0
- seaborn==0.11.2
- ipywidgets==7.6.5
